version: 2

models:
  - name: stg_timesheet
    config:
      re_data_monitored: true
      re_data_time_filter: ts
      re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3
    description: "Staging table for message data from Slack"
    columns:
      - name: user_name
        description: 'User ID in Slack'
        tests:
          - not_null
      - name: ts
        description: 'Timestamp of message in Slack'
        tests:
          - not_null
      - name: user_message
        description: "Slack message posted by user"
        tests: 
          - not_null


sources:
  - name: public
    tables:
      - name: timesheet
        config:
          re_data_monitored: true
          re_data_time_filter: ts
          re_data_anomaly_detector:
            name: modified_z_score
            threshold: 3

