version: 2

models:
  - name: fct_timesheet
    columns:
      - name: user_name
        description: 'User ID'
        tests:
          - not_null
      - name: date_ts
        description: 'Date of Workday'
        tests: 
          - not_null
      - name: day_of_week
        description: 'Day of Week'
        tests:
          - not_null
    