version: 2

models:
  - name: fct_timesheet
    config:
      re_data_monitored: true
      re_data_time_filter: date_ts
      re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3
    columns:
      - name: user_name
        description: 'User ID'
        tests:
          - not_null
      - name: date_ts
        description: 'Date of Workday'
        tests: 
          - not_null
      - name: day_of_week
        description: 'Day of Week'
        tests:
          - not_null
  - name: dim_holidays
    config:
      re_data_monitored: true
      re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3
  - name: dim_users_list
    config:
      re_data_monitored: true
      re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3
    