{
 "title": "Time Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Work Time by Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  month_name as \"Month\",\n  sum(working_hours) as \"working_hours\",\n  sum(over_time) AS \"over_time\"\nFROM fct_timesheet\nWHERE\n  $__timeFilter(date_ts)\nGROUP BY 1\n"
    }
   ]
  },
  {
   "title": "Work Time by Week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  week_of_year,\n  sum(working_hours) as \"working_hours\",\n  sum(over_time) AS \"over_time\"\nFROM fct_timesheet\nWHERE\n  $__timeFilter(date_ts)\nGROUP BY 1\norder by week_of_year asc\n\n"
    }
   ]
  },
  {
   "title": "Work Time by Day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  day_of_week,\n  working_hours,\n  over_time\nFROM fct_timesheet\nWHERE\n  $__timeFilter(date_ts)\nORDER BY date_ts desc"
    }
   ]
  },
  {
   "title": "Work Time by Cumulated by Day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_ts,\n  cum_over_time\nFROM fct_timesheet\nWHERE\n  $__timeFilter(date_ts)\nGroup By 1,2\norder by date_ts desc"
    }
   ]
  },
  {
   "title": "Working Hours Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  user_name,\n  date_ts,\n  start_time,\n  end_time,\n  month_name,\n  day_of_week,\n  working_hours,\n  over_time,\n  cum_over_time\nFROM fct_timesheet\nWHERE\n  $__timeFilter(date_ts)\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}