
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sql_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sql_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  re_data:save_test_history: true
  re_data:store_table_samples: false
  re_data:anomaly_detection_look_back_days: 30
  re_data:anomaly_detector:
      name: modified_z_score
      threshold: 2
  re_data:metrics_base:
    table:
      - row_count
      - freshness
    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - variance
        - nulls_count
        - nulls_percent
      text:
        - min_length
        - max_length
        - avg_length
        - nulls_count
        - missing_count
        - nulls_percent
        - missing_percent
  re_data:time_window_start: '{{ (run_started_at - modules.datetime.timedelta(7)).strftime("%Y-%m-%d 00:00:00") }}'
  re_data:time_window_end: '{{ run_started_at.strftime("%Y-%m-%d 00:00:00") }}'
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  sql_dbt:
    # Config indicated by + and applies to all files under models/example/
    core:
      +materialized: table
    staging:
      +materialized: table

seeds:
  sql_dbt:
    bayern_feiertage:
      +re_data_monitored: true
      +re_data_anomaly_detector:
        name: z_score
        threshold: 3